In [2]:
import numpy as np


def AND(x1, x2):
    x = np.array([x1, x2])
    w = np.array([0.5, 0.5])
    b = -0.7
    y = np.sum(w*x) + b
    return np.where(y >= 0, 1, 0)

def AND_multiple_input(x1, x2):
    x = np.array([x1, x2]).T
    w = np.array([0.5, 0.5])
    b = -0.7
    y = np.sum(w*x, axis=1) + b
    return np.where(y >= 0, 1, 0)


def NAND(x1, x2):
    x = np.array([x1, x2])
    w = np.array([-0.5, -0.5])
    b = 0.7
    y = np.sum(w*x) + b
    return np.where(y >= 0, 1, 0)

def NAND_multiple_input(x1, x2):
    x = np.array([x1, x2]).T
    w = np.array([-0.5, -0.5])
    b = 0.7
    y = np.sum(w*x, axis=1) + b
    return np.where(y >= 0, 1, 0)


def OR(x1, x2):
    x = np.array([x1, x2])
    w = np.array([0.5, 0.5])
    b = -0.3
    y = np.sum(w*x) + b
    return np.where(y >= 0, 1, 0)

def OR_multiple_input(x1, x2):
    x = np.array([x1, x2]).T
    w = np.array([0.5, 0.5])
    b = -0.3
    y = np.sum(w*x, axis=1) + b
    return np.where(y >= 0, 1, 0)


def XOR(x1, x2):
    s1 = NAND(x1, x2)
    s2 = OR(x1, x2)
    return AND(s1, s2)

def XOR_multiple_input(x1, x2):
    s1 = NAND_multiple_input(x1, x2)
    s2 = OR_multiple_input(x1, x2)
    return AND_multiple_input(s1, s2)

if __name__ == '__main__':
    for xs in [(0, 0), (1, 0), (0, 1), (1, 1)]:
        out = XOR(xs[0], xs[1])
        print(str(xs) + " -> " + str(out))

    # 複数入力
    print(XOR_multiple_input([0, 1, 0, 1], [0, 0, 1, 1]))

(0, 0) -> 0
(1, 0) -> 1
(0, 1) -> 1
(1, 1) -> 0
[0 1 1 0]


In [3]:
def sigmoid(a):
    return 1/(1 + np.power(np.e, -a))

def softmax(x):
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x)

if __name__ == '__main__':
    print(sigmoid(np.int64(4)))
    print(softmax(np.array([1, 2, 3])))

0.9820137900379085
[0.09003057 0.24472847 0.66524096]


In [8]:
import numpy as np

def init_network():
    network={}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([[0.1, 0.2, 0.3]])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([[0.1, 0.2]])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([[0.1, 0.2]])
    return network

def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    # layer 1
    a1=np.dot(x,W1)+b1
    z1=sigmoid(a1)
    # layer2 layer3を実装してみてください    
    #layer2 
    a2=np.dot(z1, W2) + b2
    z2=sigmoid(a2)
    #layer3
    a3=np.dot(z2, W3) + b3
    z3=sigmoid(a3)
    
    y=softmax(z3)
    
    
    return y

network = init_network()
x=np.array([1.0,0.5])
y=forward(network,x)
print(y) #[0.40625907, 0.59374093]

[[0.47781171 0.52218829]]


In [11]:
import numpy as np
import random  
network = init_network()
batch_size = 16
x=np.random.rand(1000,2)
for i in range(0,len(x),batch_size):
    x_batch = x[i:i+batch_size]
    y_batch = forward(network,x_batch)
    print(y_batch)

[[0.02988059 0.03263227]
 [0.02984367 0.03255068]
 [0.02986782 0.03260407]
 [0.02989025 0.03265362]
 [0.02991369 0.03270549]
 [0.02985743 0.03258106]
 [0.02988313 0.03263782]
 [0.02985935 0.03258534]
 [0.02984662 0.03255717]
 [0.02987157 0.03261229]
 [0.02986976 0.03260832]
 [0.02987441 0.03261861]
 [0.02989242 0.03265846]
 [0.02989423 0.03266248]
 [0.02991406 0.03270631]
 [0.02986633 0.0326007 ]]
[[0.02986615 0.03261684]
 [0.02987207 0.0326299 ]
 [0.02988301 0.03265419]
 [0.02986955 0.03262448]
 [0.0298539  0.03258986]
 [0.0298616  0.03260681]
 [0.02987878 0.03264483]
 [0.02989839 0.03268821]
 [0.02987166 0.03262897]
 [0.02988766 0.03266449]
 [0.02984597 0.03257225]
 [0.02986273 0.03260934]
 [0.02985372 0.03258945]
 [0.02987435 0.03263506]
 [0.02987829 0.0326437 ]
 [0.02988507 0.03265873]]
[[0.02990817 0.03270177]
 [0.02986733 0.03261148]
 [0.02988092 0.03264141]
 [0.0298837  0.03264763]
 [0.02985984 0.03259483]
 [0.02986829 0.03261352]
 [0.02990536 0.03269552]
 [0.02988897 0.03265926