# 第一回レポート課題

1. AND回路，NAND回路，OR回路を単純パーセプトロンにより表現する関数を実装し，真理値表通り，出力されるか確認して下さい．
関数名は各々，AND(x1, x2), NAND(x1, x2), OR(x1, x2)として，1か０を引数に取れるようにして下さい．
2. 上記で実装した関数の組み合わせにより，XOR回路を実装し，真理値表通り，出力されるか確認して下さい．
関数名は，XOR(x1, x2)として，，1か０を引数に取れるようにして下さい．

論理演算を実装した。  
` *_multiple_input`で複数入力を実装した。

In [10]:
import numpy as np


def AND(x1, x2):
    x = np.array([x1, x2])
    w = np.array([0.5, 0.5])
    b = -0.7
    y = np.sum(w*x) + b
    return np.where(y >= 0, 1, 0)

def AND_multiple_input(x1, x2):
    x = np.array([x1, x2]).T
    w = np.array([0.5, 0.5])
    b = -0.7
    y = np.sum(w*x, axis=1) + b
    return np.where(y >= 0, 1, 0)


def NAND(x1, x2):
    x = np.array([x1, x2])
    w = np.array([-0.5, -0.5])
    b = 0.7
    y = np.sum(w*x) + b
    return np.where(y >= 0, 1, 0)

def NAND_multiple_input(x1, x2):
    x = np.array([x1, x2]).T
    w = np.array([-0.5, -0.5])
    b = 0.7
    y = np.sum(w*x, axis=1) + b
    return np.where(y >= 0, 1, 0)


def OR(x1, x2):
    x = np.array([x1, x2])
    w = np.array([0.5, 0.5])
    b = -0.3
    y = np.sum(w*x) + b
    return np.where(y >= 0, 1, 0)

def OR_multiple_input(x1, x2):
    x = np.array([x1, x2]).T
    w = np.array([0.5, 0.5])
    b = -0.3
    y = np.sum(w*x, axis=1) + b
    return np.where(y >= 0, 1, 0)


def XOR(x1, x2):
    s1 = NAND(x1, x2)
    s2 = OR(x1, x2)
    return AND(s1, s2)

def XOR_multiple_input(x1, x2):
    s1 = NAND_multiple_input(x1, x2)
    s2 = OR_multiple_input(x1, x2)
    return AND_multiple_input(s1, s2)

if __name__ == '__main__':
    for xs in [(0, 0), (1, 0), (0, 1), (1, 1)]:
        out = XOR(xs[0], xs[1])
        print(str(xs) + " -> " + str(out))

    # 複数入力
    print(XOR_multiple_input([0, 1, 0, 1], [0, 0, 1, 1]))

(0, 0) -> 0
(1, 0) -> 1
(0, 1) -> 1
(1, 1) -> 0
[0 1 1 0]


3. 活性化関数であるSigmoid関数とSoftmax関数をpythonで実装して下さい．Sigmoid関数は次の課題でそのまま使用するので、Numpyを入力としてください

In [11]:
def sigmoid(a):
    return 1/(1 + np.power(np.e, -a))

def softmax(x):
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x)

if __name__ == '__main__':
    print(sigmoid(np.int64(4)))
    print(softmax(np.array([1, 2, 3])))

0.9820137900379085
[0.09003057 0.24472847 0.66524096]


4. 3層マルチパーセプトロンによるNNの実装を行い、出力が正しいか確認してください．下記のサンプルコードにおけるforward部分を実装してみてください. 中間層の活性化関数にはSigmoid関数、出力層の関数にはSoftmax関数を使ってください。

In [12]:
def init_network():
    network={}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([[0.1, 0.2, 0.3]])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([[0.1, 0.2]])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([[0.1, 0.2]])
    return network

def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    # layer 1
    a1=np.dot(x,W1)+b1
    z1=sigmoid(a1)
    # layer2 layer3を実装してみてください    
    #layer2 
    a2=np.dot(z1, W2) + b2
    z2=sigmoid(a2)
    #layer3
    a3=np.dot(z2, W3) + b3
    z3=sigmoid(a3)
    
    y=softmax(z3)
    
    
    return y

network = init_network()
x=np.array([1.0,0.5])
y=forward(network,x)
print(y) #[0.40625907, 0.59374093]

[[0.47781171 0.52218829]]


5. バッチ処理の行い方についてサンプルコードを実行し、扱い方のイメージを掴んでください．

In [ ]:
import random  

network = init_network()
batch_size = 16
x=np.random.rand(1000,2)
for i in range(0,len(x),batch_size):
    x_batch = x[i:i+batch_size]
    y_batch = forward(network,x_batch)
    print(y_batch)

## 感想

行列を使って示すことで非線形関数をレイヤーのたびに使うの必要性を理解できたが、なぜsigmoid関数が選ばれたのか気になる。他の関数と比較したい。